version: '2'
services:
    four_for_belot-app:
        image: four_for_belot
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://four_for_belot-postgresql:5432/four_for_belot
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    four_for_belot-postgresql:
        extends:
            file: postgresql.yml
            service: four_for_belot-postgresql
